files:
  - source: /Source/Resources/Data/Translations/en.json
    translation: /Source/Resources/Data/Translations/%two_letters_code%.json
    parser: json
    json:
      translate_paths:
        - /*/*/translatedName
        - /*/*/intro
        - /*/*/about
        - /*/*/ranch
        - /*/*/type
        - /*/*/favouredBy
        - /additional/ui/*
        - /additional/pedia/*
        - /slimes/*/risks
        - /slimes/*/slimeology
        - /slimes/*/diet
        - /slimes/*/favourite
        - /slimes/*/onomics
        - /ranchers/*/offers/*
        - /ranchers/*/specialOffer
        - /ranchers/*/loadingTexts/*
        - /zones/*/presence
        - /zones/*/description
        - /mail/*/subject
        - /mail/*/body
      excluded_paths:
        - /*/name
        - /name
        - /*/*/name
        - /mail/*/mailKey