<Project>
  <Target Name="Copy" AfterTargets="Build"> <!-- This will create new directories if you don't have them made already -->
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(MSBuildThisFileDirectory)/Mods/" Condition="$(Configuration)!=Unity" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(MSBuildThisFileDirectory)/Bundle/Assets/Plugins" Condition="$(Configuration)==Unity" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(MSBuildThisFileDirectory)/Scripting/Assets/Plugins" Condition="$(Configuration)==Unity" />
  </Target>

  <ItemGroup Condition="$(Configuration)!=Unity">
    <Reference Include="$(MSBuildThisFileDirectory)/Libs/*.dll" PrivateAssets="all" ExcludeAssets="runtime" />
    <Reference Include="$(MSBuildThisFileDirectory)/SrLibs/*.dll" PrivateAssets="all" ExcludeAssets="runtime" />
    <Reference Include="$(MSBuildThisFileDirectory)/SrmlLibs/*.dll" PrivateAssets="all" ExcludeAssets="runtime" />
  </ItemGroup>

  <ItemGroup Condition="$(Configuration)==Unity">
    <Reference Include="$(MSBuildThisFileDirectory)/SrmlLibs/Newtonsoft.Json.dll" PrivateAssets="all" ExcludeAssets="runtime" />
  </ItemGroup>
</Project>