<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>OceanRange</AssemblyName>
    <RootNamespace>OceanRange</RootNamespace>
    <Version>0.3.0</Version>
    <DebugSymbols>true</DebugSymbols>
    <LangVersion>preview</LangVersion>
    <nullable>enable</nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Authors>TheRanchExchange</Authors>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
    <Description>Dive into the slime sea!</Description>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <Configurations>Debug;Release;Unity</Configurations>
    <PublicizerClearCacheOnClean>true</PublicizerClearCacheOnClean>
  </PropertyGroup>

  <PropertyGroup Condition="$(Configuration)==Unity">
    <DefineConstants>UNITY</DefineConstants>
    <DebugType>embedded</DebugType>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="$(Configuration)==Debug">
    <DebugType>none</DebugType>
    <TargetFramework>net4.7.2</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="$(Configuration)==Release">
    <Optimize>true</Optimize>
    <DebugType>none</DebugType>
    <TargetFramework>net4.7.2</TargetFramework>
  </PropertyGroup>

  <ItemGroup Condition="$(Configuration)!=Unity">
    <PackageReference Include="Krafs.Publicizer" Version="2.3.0" PrivateAssets="all" ExcludeAssets="runtime" />
    <PackageReference Include="Roslynator.Analyzers" Version="4.15.0" PrivateAssets="all" ExcludeAssets="runtime" />
    <PackageReference Include="Roslynator.Formatting.Analyzers" Version="4.15.0" PrivateAssets="all" ExcludeAssets="runtime" />
    <PackageReference Include="Roslynator.CodeAnalysis.Analyzers" Version="4.15.0" PrivateAssets="all" ExcludeAssets="runtime" />

    <EmbeddedResource Include="Resources\*" />
    <EmbeddedResource Include="Resources\*\*" />
    <EmbeddedResource Include="Resources\*\*\*" />

    <Publicize Include="Assembly-CSharp" IncludeCompilerGeneratedMembers="false" />
    <Publicize Include="UnityEngine.CoreModule" />

    <Compile Remove="Unity\*.cs" />
  </ItemGroup>

  <ItemGroup Condition="$(Configuration)==Unity">
    <Compile Remove="**\*.cs" />

    <Compile Include="GlobalUsings.cs" />
    <Compile Include="Data\DataWriter.cs" />
    <Compile Include="Data\StringPooler.cs" />
    <Compile Include="Utils\UnityUtils.cs" />
    <Compile Include="Unity\*.cs" />
    <Compile Include="Common\*.cs" />
    <Compile Include="Data\Common\*.cs" />
    <Compile Include="Data\Unity\*.cs" />
    <Compile Include="System\*.cs" />
    <Compile Include="Slimes\FlashbangEffect.cs" />
  </ItemGroup>

  <Import Project="../SlimeRancher.props" />
</Project>